const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const Module = require('node:module');
require.extensions['.ts'] = (m, f) => m._compile(ts.transpileModule(fs.readFileSync(f, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, esModuleInterop: true } }).outputText, f);
const c = require('../utils/benchCalculators.ts');
assert.equal(c.combineResistors('100, 220, 470', false), 790);
assert.equal(c.combineResistors('100,100', true), 50);
for (const value of ['100', '100,-2', '1,0', '1,Infinity', '1,2x']) assert.throws(() => c.combineResistors(value, true));
assert.equal(c.capacitorCode('104').pf, 100000);
assert.deepEqual(c.capacitorCode('472J'), { pf: 4700, tolerance: '±5%' });
assert.throws(() => c.capacitorCode('R'));
assert.throws(() => c.capacitorCode('104XYZ'));
assert.deepEqual(c.reverseResistor(4700, 2, 5).map(v => v.name), ['Yellow', 'Violet', 'Red', 'Gold']);
assert.deepEqual(c.reverseResistor(2490, 3, 1).map(v => v.name), ['Red', 'Yellow', 'White', 'Brown', 'Brown']);
assert.throws(() => c.reverseResistor(2490, 2, 5));
assert.throws(() => c.reverseResistor(0, 2, 5));
let release;
const stored = new Map();
const original = Module._load;
Module._load = function(request, parent, main) {
  if (request === '@react-native-async-storage/async-storage') return { getItem: () => new Promise(resolve => { release = resolve; }), setItem: async (k, v) => { stored.set(k, v); } };
  return original.call(this, request, parent, main);
};
(async () => {
  const b = require('../utils/benchStore.ts');
  const a = { id: 'ic:lm358', title: 'LM358', route: '/tools/ic-guide?ic=lm358' };
  const loading = b.loadBench();
  const saving = b.toggleFavorite(a);
  release(JSON.stringify({ favorites: [{ id: 'old', title: 'Old', route: '/tools/library' }], recent: [], calculations: [], jobs: [] }));
  await loading; await saving;
  let data = () => JSON.parse(stored.get('bench.library.v1'));
  assert.equal(data().favorites.length, 2, 'late hydration must preserve the earlier favorite');
  await b.recordRecent(a); await b.recordRecent(a);
  assert.equal(data().recent.length, 1);
  await Promise.all([b.saveCalculation('1 Ω'), b.saveCalculation('2 Ω')]);
  assert.deepEqual(data().calculations, ['2 Ω', '1 Ω']);
  await b.toggleFavorite(a);
  assert.equal(data().favorites.length, 1);
  console.log('Bench calculator and persistent library checks passed.');
})().catch(e => { console.error(e); process.exitCode = 1; }).finally(() => { Module._load = original; });
